### ISSUE TITLE
I want to add N Queen Problem in java.

### ISSUE THREAD

**Issue by FaisalAI541** [frigid-lynx/Hacktoberfest2022#47]
The N Queen is the problem of placing N chess queens on an N×N chessboard so that no two queens attack each other. For example, the following is a solution for the 4 Queen problem.

**Comment by frigid-lynx** [comment]
Please add it in my Cpp-DSA repository i will merge it(code it using cpp)

**Comment by FaisalAI541** [comment]
ok i will do it

**Comment by SAURABHTIWARIVBSPU** [comment]
please asign this issue for me i can slove it

**Comment by frigid-lynx** [comment]
Please add it in my other repo cpp DSA code it in cpp i will merge it

**Comment by frigid-lynx** [comment]
Please add it in my Cpp-DSA repository i will merge it(code it using cpp) @SAURABHTIWARIVBSPU
