### ISSUE TITLE
Can I add Depth First Search Algorithm.

### ISSUE THREAD

**Issue by FaisalAI541** [frigid-lynx/Hacktoberfest2022#49]
Depth-first search is an algorithm for traversing or searching tree or graph data structures. The algorithm starts at the root node and explores as far as possible along each branch before backtracking.

**Comment by frigid-lynx** [comment]
Please add it in cpp DSA repo k will merge it(code it in cpp)

**Comment by FaisalAI541** [comment]
Plz assign me to the hactoberfest repo so that it can be counted in hactoberfest contributions.

**Comment by frigid-lynx** [comment]
Please add it in my other repo cpp DSA ( choose some complex algo which is
not already in repo)

**Comment by SAURABHTIWARIVBSPU** [comment]
please asign this issue for me i can slove it

**Comment by frigid-lynx** [comment]
Please add it in my other repo cpp dsa in c++

**Comment by SAURABHTIWARIVBSPU** [comment]
Please add it in my other repo cpp dsa in c++
