### ISSUE TITLE
Can I add the java program for Order Agnostic Binary Search

### ISSUE THREAD

**Issue by FaisalAI541** [frigid-lynx/Hacktoberfest2022#54]
Plz allow me

**Comment by frigid-lynx** [comment]
Please add it in in my cpp DSA repo i will surely merge it add something
that is bit unique and complex algo in cpp

**Comment by FaisalAI541** [comment]
ok

**Comment by FaisalAI541** [comment]
but cpp DSA repo is not eligible for Hacktoberfest ?

**Comment by frigid-lynx** [comment]
Yes, it is.

**Comment by FaisalAI541** [comment]
there is no hacktoberfest tag on cpp DSA repo

**Comment by frigid-lynx** [comment]
i will add it for the pull request after accepting it

**Comment by FaisalAI541** [comment]
ok
