### ISSUE TITLE
22. Generate Parentheses

### ISSUE THREAD

**Issue by Gaurika-Gupta** [frigid-lynx/Hacktoberfest2022#73]
Java solution of Leetcode problem - https://leetcode.com/problems/generate-parentheses/

**Comment by Gaurika-Gupta** [comment]
Please assign me this Issue under Hacktoberfest 2022 after adding necessary Labels

**Comment by frigid-lynx** [comment]
Please add in my other repo named(" DSA Algo") repository for hacktoberfest 2022 as this repo is excluded from hacktoberfest
